export const links = {
  home: "/",
  about: "/about",
  gallery: "/gallery",
  galleryName: "/gallery/:name",
  galleryNamePage: "/gallery/:name/:page",
  galleryDetail: "/gallery/:name/:page/:id",
  newsBase: "/news",
  news: "/news/:page",
  newsLink: "/news/1",
  newsDetail: "/news/:page/:id",
  booking: "/booking",
  contacts: "/contacts",
  clubs: "/clubs",
  club: "/clubs/:id",
  rules: "/rules",
  clientAgreement: "/client-agreement",
  reg: "/sign-up",
  login: "/sign-in",
  success: "/activate/:uid/:token",
  account: "/account",
  admin: "/account/admin",
  adminMainMap: "/account/admin/admin-main-map",
  adminClub: "/account/admin/club",
  adminClubAdd: "/account/admin/club/add-club",
  adminClubAddContacts: "/account/admin/club/add-club-contacts",
  adminClubAddComputer: "/account/admin/club/add-club-computer",
  adminClubAddSpec: "/account/admin/club/add-club-spec",
  adminClubAddPrice: "/account/admin/club/add-club-price",
  adminGallery: "/account/admin/gallery",
  adminGalleryAddPhoto: "/account/admin/gallery/add-photo",
  adminGalleryRemove: "/account/admin/gallery/remove-photo",
  adminNews: "/account/admin/news",
  adminNewsAdd: "/account/admin/news/add-news",
  adminPartners: "/account/admin/partners",
  adminPartnersAdd: "/account/admin/partners/add-partner",
  adminPartnersRemove: "/account/admin/partners/remove-partner",
  technicalWorks: "/plasholder",
};

export const socialLinks = {
  instagram: "https://www.instagram.com/pudge_cyberclub/",
  telegram: "",
  vk: "https://vk.com/pudgecyberclub",
  mail: "mailto:example@example.com",
  tiktok: "https://www.tiktok.com/@pudge_cyber_club?_t=8epOCODmLQM&_r=1",
};
