import { type FormField } from "./AddPrice.type";

export const addPriceFormSchema: FormField[] = [
  {
    label: "Название клуба",
    placeholder: "Введите название клуба",
    name: "name",
    type: "text",
  },
  {
    label: "Тариф",
    placeholder: "vip comfort bootcamp",
    name: "tariff",
    type: "text",
  },
  {
    label: "Первый ряд",
    placeholder: "section",
    name: "section",
    type: "section",
  },
  {
    label: "Подтариф",
    subLabel: "1 ряд 1 ячейка",
    placeholder: `Например НОЧЬ+`,
    name: "oneRowOneСel",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "1 ряд 2 ячейка",
    placeholder: "Например 5",
    name: "oneRowTwoСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "1 ряд 2 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "oneRowTwoСelDesc",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "1 ряд 3 ячейка",
    placeholder: "Например 5",
    name: "oneRowThreeСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "1 ряд 3 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "oneRowThreeСelDesc",
    type: "text",
  },
  {
    label: "Второй ряд",
    placeholder: "section",
    name: "section",
    type: "section",
  },
  {
    label: `Подтариф`,
    subLabel: "2 ряд 1 ячейка",
    placeholder: "Например НОЧЬ+",
    name: "twoRowOneСel",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "2 ряд 2 ячейка",
    placeholder: "Например 5",
    name: "twoRowTwoСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "2 ряд 2 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "twoRowTwoСelDesc",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "2 ряд 3 ячейка",
    placeholder: "Например 5",
    name: "twoRowThreeСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "2 ряд 3 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "twoRowThreeСelDesc",
    type: "text",
  },
  {
    label: "Третий ряд",
    placeholder: "section",
    name: "section",
    type: "section",
  },
  {
    label: "Подтариф",
    subLabel: "3 ряд 1 ячейка",
    placeholder: "Например НОЧЬ+",
    name: "threeRowOneСel",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "3 ряд 2 ячейка",
    placeholder: "Например 5",
    name: "threeRowTwoСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "3 ряд 2 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "threeRowTwoСelDesc",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "3 ряд 3 ячейка",
    placeholder: "Например 5",
    name: "threeRowThreeСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "3 ряд 3 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "threeRowThreeСelDesc",
    type: "text",
  },
  {
    label: "Четвёртый ряд",
    placeholder: "section",
    name: "section",
    type: "section",
  },
  {
    label: "Подтариф",
    subLabel: "4 ряд 1 ячейка",
    placeholder: "Например НОЧЬ+",
    name: "fourRowOneСel",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "4 ряд 2 ячейка",
    placeholder: "Например 5",
    name: "fourRowTwoСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "4 ряд 2 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "fourRowTwoСelDesc",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "4 ряд 3 ячейка",
    placeholder: "Например 5",
    name: "fourRowThreeСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "4 ряд 3 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "fourRowThreeСelDesc",
    type: "text",
  },
  {
    label: "Пятый ряд",
    placeholder: "section",
    name: "section",
    type: "section",
  },
  {
    label: "Подтариф",
    subLabel: "5 ряд 1 ячейка",
    placeholder: "Например НОЧЬ+",
    name: "fiveRowOneСel",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "5 ряд 2 ячейка",
    placeholder: "Например 5",
    name: "fiveRowTwoСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "5 ряд 2 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "fiveRowTwoСelDesc",
    type: "text",
  },
  {
    label: "Цена",
    subLabel: "5 ряд 3 ячейка",
    placeholder: "Например 5",
    name: "fiveRowThreeСel",
    type: "text",
  },
  {
    label: "Пояснение",
    subLabel: "5 ряд 3 ячейка",
    placeholder: "Например 15:00 - 19:00",
    name: "fiveRowThreeСelDesc",
    type: "text",
  },
  {
    label: "Дополнеиня",
    placeholder: "section",
    name: "section",
    type: "section",
  },
  {
    label: "Дополнение 1",
    subLabel: "Внизу таблицы",
    placeholder: "Какой-то текст",
    name: "DescrOne",
    type: "text",
  },
  {
    label: "Дополнение 2",
    subLabel: "Внизу таблицы",
    placeholder: "Какой-то текст",
    name: "DescrTwo",
    type: "text",
  },
  {
    label: "Дополнение 3",
    subLabel: "Внизу таблицы",
    placeholder: "Какой-то текст",
    name: "DescrThree",
    type: "text",
  },
  {
    label: "Дополнение 4",
    subLabel: "Внизу таблицы",
    placeholder: "Какой-то текст",
    name: "DescrFour",
    type: "text",
  },
  {
    label: "Дополнение 5",
    subLabel: "Внизу таблицы",
    placeholder: "Какой-то текст",
    name: "DescrFive",
    type: "text",
  },
];
